upstream_package_name: adw-gtk3
downstream_package_name: adw-gtk3-theme
upstream_project_url: https://github.com/lassekongo83/adw-gtk3
upstream_tag_template: v{version}

jobs:
  - job: pull_from_upstream
    trigger: release
    dist_git_branches:
      - fedora-rawhide

  - job: koji_build
    trigger: commit
    allowed_pr_authors: ['packit', 'solopasha']
    allowed_committers: ['packit', 'solopasha']
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
